<?php

namespace App\Migration;

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;

class NegaraMigration
{
    public function createTable ()
    {
        if(!Capsule::schema()->hasTable('negara'))
        {
            Capsule::schema()->create('negara', function (Blueprint $table)
            {
                $table->integer('id');
                $table->string('nama');
                $table->integer('urutan')->default(0);
                $table->integer('user')->default(1);
                $table->timestamps();
                $table->primary('id');
            });

            $this->seed();
        }
    }

    public function seed()
    {
        // Negara
        $negara = array(
            array('id' => '1','nama' => 'Afghanistan'),
            array('id' => '2','nama' => 'Albania'),
            array('id' => '3','nama' => 'Algeria'),
            array('id' => '4','nama' => 'American Samoa'),
            array('id' => '5','nama' => 'Andorra'),
            array('id' => '6','nama' => 'Angola'),
            array('id' => '7','nama' => 'Anguilla'),
            array('id' => '8','nama' => 'Antarctica'),
            array('id' => '9','nama' => 'Antigua and Barbuda'),
            array('id' => '10','nama' => 'Argentina'),
            array('id' => '11','nama' => 'Armenia'),
            array('id' => '12','nama' => 'Aruba'),
            array('id' => '13','nama' => 'Australia'),
            array('id' => '14','nama' => 'Austria'),
            array('id' => '15','nama' => 'Azerbaijan'),
            array('id' => '16','nama' => 'Bahamas'),
            array('id' => '17','nama' => 'Bahrain'),
            array('id' => '18','nama' => 'Bangladesh'),
            array('id' => '19','nama' => 'Barbados'),
            array('id' => '20','nama' => 'Belarus'),
            array('id' => '21','nama' => 'Belgium'),
            array('id' => '22','nama' => 'Belize'),
            array('id' => '23','nama' => 'Benin'),
            array('id' => '24','nama' => 'Bermuda'),
            array('id' => '25','nama' => 'Bhutan'),
            array('id' => '26','nama' => 'Bolivia'),
            array('id' => '27','nama' => 'Bosnia and Herzegovina'),
            array('id' => '28','nama' => 'Botswana'),
            array('id' => '29','nama' => 'Bouvet Island'),
            array('id' => '30','nama' => 'Brazil'),
            array('id' => '31','nama' => 'British Indian Ocean Territory'),
            array('id' => '32','nama' => 'Brunei Darussalam'),
            array('id' => '33','nama' => 'Bulgaria'),
            array('id' => '34','nama' => 'Burkina Faso'),
            array('id' => '35','nama' => 'Burundi'),
            array('id' => '36','nama' => 'Cambodia'),
            array('id' => '37','nama' => 'Cameroon'),
            array('id' => '38','nama' => 'Canada'),
            array('id' => '39','nama' => 'Cape Verde'),
            array('id' => '40','nama' => 'Cayman Islands'),
            array('id' => '41','nama' => 'Central African Republic'),
            array('id' => '42','nama' => 'Chad'),
            array('id' => '43','nama' => 'Chile'),
            array('id' => '44','nama' => 'China'),
            array('id' => '45','nama' => 'Christmas Island'),
            array('id' => '46','nama' => 'Cocos (Keeling) Islands'),
            array('id' => '47','nama' => 'Colombia'),
            array('id' => '48','nama' => 'Comoros'),
            array('id' => '49','nama' => 'Congo'),
            array('id' => '50','nama' => 'Cook Islands'),
            array('id' => '51','nama' => 'Costa Rica'),
            array('id' => '52','nama' => 'Croatia (Hrvatska)'),
            array('id' => '53','nama' => 'Cuba'),
            array('id' => '54','nama' => 'Cyprus'),
            array('id' => '55','nama' => 'Czech Republic'),
            array('id' => '56','nama' => 'Denmark'),
            array('id' => '57','nama' => 'Djibouti'),
            array('id' => '58','nama' => 'Dominica'),
            array('id' => '59','nama' => 'Dominican Republic'),
            array('id' => '60','nama' => 'East Timor'),
            array('id' => '61','nama' => 'Ecuador'),
            array('id' => '62','nama' => 'Egypt'),
            array('id' => '63','nama' => 'El Salvador'),
            array('id' => '64','nama' => 'Equatorial Guinea'),
            array('id' => '65','nama' => 'Eritrea'),
            array('id' => '66','nama' => 'Estonia'),
            array('id' => '67','nama' => 'Ethiopia'),
            array('id' => '68','nama' => 'Falkland Islands (Malvinas)'),
            array('id' => '69','nama' => 'Faroe Islands'),
            array('id' => '70','nama' => 'Fiji'),
            array('id' => '71','nama' => 'Finland'),
            array('id' => '72','nama' => 'France'),
            array('id' => '73','nama' => 'France, Metropolitan'),
            array('id' => '74','nama' => 'French Guiana'),
            array('id' => '75','nama' => 'French Polynesia'),
            array('id' => '76','nama' => 'French Southern Territories'),
            array('id' => '77','nama' => 'Gabon'),
            array('id' => '78','nama' => 'Gambia'),
            array('id' => '79','nama' => 'Georgia'),
            array('id' => '80','nama' => 'Germany'),
            array('id' => '81','nama' => 'Ghana'),
            array('id' => '82','nama' => 'Gibraltar'),
            array('id' => '83','nama' => 'Guernsey'),
            array('id' => '84','nama' => 'Greece'),
            array('id' => '85','nama' => 'Greenland'),
            array('id' => '86','nama' => 'Grenada'),
            array('id' => '87','nama' => 'Guadeloupe'),
            array('id' => '88','nama' => 'Guam'),
            array('id' => '89','nama' => 'Guatemala'),
            array('id' => '90','nama' => 'Guinea'),
            array('id' => '91','nama' => 'Guinea-Bissau'),
            array('id' => '92','nama' => 'Guyana'),
            array('id' => '93','nama' => 'Haiti'),
            array('id' => '94','nama' => 'Heard and Mc Donald Islands'),
            array('id' => '95','nama' => 'Honduras'),
            array('id' => '96','nama' => 'Hong Kong'),
            array('id' => '97','nama' => 'Hungary'),
            array('id' => '98','nama' => 'Iceland'),
            array('id' => '99','nama' => 'India'),
            array('id' => '100','nama' => 'Isle of Man'),
            array('id' => '101','nama' => 'Indonesia'),
            array('id' => '102','nama' => 'Iran (Islamic Republic of)'),
            array('id' => '103','nama' => 'Iraq'),
            array('id' => '104','nama' => 'Ireland'),
            array('id' => '105','nama' => 'Israel'),
            array('id' => '106','nama' => 'Italy'),
            array('id' => '107','nama' => 'Ivory Coast'),
            array('id' => '108','nama' => 'Jersey'),
            array('id' => '109','nama' => 'Jamaica'),
            array('id' => '110','nama' => 'Japan'),
            array('id' => '111','nama' => 'Jordan'),
            array('id' => '112','nama' => 'Kazakhstan'),
            array('id' => '113','nama' => 'Kenya'),
            array('id' => '114','nama' => 'Kiribati'),
            array('id' => '115','nama' => 'Korea, Democratic People\'s Republic of'),
            array('id' => '116','nama' => 'Korea, Republic of'),
            array('id' => '117','nama' => 'Kosovo'),
            array('id' => '118','nama' => 'Kuwait'),
            array('id' => '119','nama' => 'Kyrgyzstan'),
            array('id' => '120','nama' => 'Lao People\'s Democratic Republic'),
            array('id' => '121','nama' => 'Latvia'),
            array('id' => '122','nama' => 'Lebanon'),
            array('id' => '123','nama' => 'Lesotho'),
            array('id' => '124','nama' => 'Liberia'),
            array('id' => '125','nama' => 'Libyan Arab Jamahiriya'),
            array('id' => '126','nama' => 'Liechtenstein'),
            array('id' => '127','nama' => 'Lithuania'),
            array('id' => '128','nama' => 'Luxembourg'),
            array('id' => '129','nama' => 'Macau'),
            array('id' => '130','nama' => 'Macedonia'),
            array('id' => '131','nama' => 'Madagascar'),
            array('id' => '132','nama' => 'Malawi'),
            array('id' => '133','nama' => 'Malaysia'),
            array('id' => '134','nama' => 'Maldives'),
            array('id' => '135','nama' => 'Mali'),
            array('id' => '136','nama' => 'Malta'),
            array('id' => '137','nama' => 'Marshall Islands'),
            array('id' => '138','nama' => 'Martinique'),
            array('id' => '139','nama' => 'Mauritania'),
            array('id' => '140','nama' => 'Mauritius'),
            array('id' => '141','nama' => 'Mayotte'),
            array('id' => '142','nama' => 'Mexico'),
            array('id' => '143','nama' => 'Micronesia, Federated States of'),
            array('id' => '144','nama' => 'Moldova, Republic of'),
            array('id' => '145','nama' => 'Monaco'),
            array('id' => '146','nama' => 'Mongolia'),
            array('id' => '147','nama' => 'Montenegro'),
            array('id' => '148','nama' => 'Montserrat'),
            array('id' => '149','nama' => 'Morocco'),
            array('id' => '150','nama' => 'Mozambique'),
            array('id' => '151','nama' => 'Myanmar'),
            array('id' => '152','nama' => 'Namibia'),
            array('id' => '153','nama' => 'Nauru'),
            array('id' => '154','nama' => 'Nepal'),
            array('id' => '155','nama' => 'Netherlands'),
            array('id' => '156','nama' => 'Netherlands Antilles'),
            array('id' => '157','nama' => 'New Caledonia'),
            array('id' => '158','nama' => 'New Zealand'),
            array('id' => '159','nama' => 'Nicaragua'),
            array('id' => '160','nama' => 'Niger'),
            array('id' => '161','nama' => 'Nigeria'),
            array('id' => '162','nama' => 'Niue'),
            array('id' => '163','nama' => 'Norfolk Island'),
            array('id' => '164','nama' => 'Northern Mariana Islands'),
            array('id' => '165','nama' => 'Norway'),
            array('id' => '166','nama' => 'Oman'),
            array('id' => '167','nama' => 'Pakistan'),
            array('id' => '168','nama' => 'Palau'),
            array('id' => '169','nama' => 'Palestine'),
            array('id' => '170','nama' => 'Panama'),
            array('id' => '171','nama' => 'Papua New Guinea'),
            array('id' => '172','nama' => 'Paraguay'),
            array('id' => '173','nama' => 'Peru'),
            array('id' => '174','nama' => 'Philippines'),
            array('id' => '175','nama' => 'Pitcairn'),
            array('id' => '176','nama' => 'Poland'),
            array('id' => '177','nama' => 'Portugal'),
            array('id' => '178','nama' => 'Puerto Rico'),
            array('id' => '179','nama' => 'Qatar'),
            array('id' => '180','nama' => 'Reunion'),
            array('id' => '181','nama' => 'Romania'),
            array('id' => '182','nama' => 'Russian Federation'),
            array('id' => '183','nama' => 'Rwanda'),
            array('id' => '184','nama' => 'Saint Kitts and Nevis'),
            array('id' => '185','nama' => 'Saint Lucia'),
            array('id' => '186','nama' => 'Saint Vincent and the Grenadines'),
            array('id' => '187','nama' => 'Samoa'),
            array('id' => '188','nama' => 'San Marino'),
            array('id' => '189','nama' => 'Sao Tome and Principe'),
            array('id' => '190','nama' => 'Saudi Arabia'),
            array('id' => '191','nama' => 'Senegal'),
            array('id' => '192','nama' => 'Serbia'),
            array('id' => '193','nama' => 'Seychelles'),
            array('id' => '194','nama' => 'Sierra Leone'),
            array('id' => '195','nama' => 'Singapore'),
            array('id' => '196','nama' => 'Slovakia'),
            array('id' => '197','nama' => 'Slovenia'),
            array('id' => '198','nama' => 'Solomon Islands'),
            array('id' => '199','nama' => 'Somalia'),
            array('id' => '200','nama' => 'South Africa'),
            array('id' => '201','nama' => 'South Georgia South Sandwich Islands'),
            array('id' => '202','nama' => 'Spain'),
            array('id' => '203','nama' => 'Sri Lanka'),
            array('id' => '204','nama' => 'St. Helena'),
            array('id' => '205','nama' => 'St. Pierre and Miquelon'),
            array('id' => '206','nama' => 'Sudan'),
            array('id' => '207','nama' => 'Suriname'),
            array('id' => '208','nama' => 'Svalbard and Jan Mayen Islands'),
            array('id' => '209','nama' => 'Swaziland'),
            array('id' => '210','nama' => 'Sweden'),
            array('id' => '211','nama' => 'Switzerland'),
            array('id' => '212','nama' => 'Syrian Arab Republic'),
            array('id' => '213','nama' => 'Taiwan'),
            array('id' => '214','nama' => 'Tajikistan'),
            array('id' => '215','nama' => 'Tanzania, United Republic of'),
            array('id' => '216','nama' => 'Thailand'),
            array('id' => '217','nama' => 'Togo'),
            array('id' => '218','nama' => 'Tokelau'),
            array('id' => '219','nama' => 'Tonga'),
            array('id' => '220','nama' => 'Trinidad and Tobago'),
            array('id' => '221','nama' => 'Tunisia'),
            array('id' => '222','nama' => 'Turkey'),
            array('id' => '223','nama' => 'Turkmenistan'),
            array('id' => '224','nama' => 'Turks and Caicos Islands'),
            array('id' => '225','nama' => 'Tuvalu'),
            array('id' => '226','nama' => 'Uganda'),
            array('id' => '227','nama' => 'Ukraine'),
            array('id' => '228','nama' => 'United Arab Emirates'),
            array('id' => '229','nama' => 'United Kingdom'),
            array('id' => '230','nama' => 'United States'),
            array('id' => '231','nama' => 'United States minor outlying islands'),
            array('id' => '232','nama' => 'Uruguay'),
            array('id' => '233','nama' => 'Uzbekistan'),
            array('id' => '234','nama' => 'Vanuatu'),
            array('id' => '235','nama' => 'Vatican City State'),
            array('id' => '236','nama' => 'Venezuela'),
            array('id' => '237','nama' => 'Vietnam'),
            array('id' => '238','nama' => 'Virgin Islands (British)'),
            array('id' => '239','nama' => 'Virgin Islands (U.S.)'),
            array('id' => '240','nama' => 'Wallis and Futuna Islands'),
            array('id' => '241','nama' => 'Western Sahara'),
            array('id' => '242','nama' => 'Yemen'),
            array('id' => '243','nama' => 'Yugoslavia'),
            array('id' => '244','nama' => 'Zaire'),
            array('id' => '245','nama' => 'Zambia'),
            array('id' => '246','nama' => 'Zimbabwe')
            );

        Capsule::table('negara')->insert($negara);
    }
}
 