<?php

namespace App\Migration;

use Illuminate\Database\Capsule\Manager as Capsule;
use Illuminate\Database\Schema\Blueprint;

class ResourceActionMigration
{
    public function createTable ()
    {
        Capsule::schema()->dropIfExists('resource_actions');
        Capsule::schema()->create('resource_actions', function (Blueprint $table)
        {
            $table->increments('id');
            $table->integer('resource_id');
            $table->string('name');
            $table->string('route_name');
            $table->integer('sequence');
            $table->timestamps();
        });

        $resource_actions = array(
                                array('id' => '5','resource_id' => '1','name' => 'tampil','route_name' => 'accounting-accounts','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '6','resource_id' => '1','name' => 'tambah','route_name' => 'accounting-accounts-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '7','resource_id' => '1','name' => 'ubah','route_name' => 'accounting-accounts-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '8','resource_id' => '1','name' => 'hapus','route_name' => 'accounting-accounts-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '9','resource_id' => '2','name' => 'tampil','route_name' => 'accounting-headers','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '10','resource_id' => '2','name' => 'tambah','route_name' => 'accounting-headers-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '11','resource_id' => '2','name' => 'ubah','route_name' => 'accounting-headers-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '12','resource_id' => '2','name' => 'hapus','route_name' => 'accounting-headers-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '13','resource_id' => '3','name' => 'tampil','route_name' => 'accounting-jurnal','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '14','resource_id' => '3','name' => 'tambah','route_name' => 'accounting-jurnal-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '15','resource_id' => '3','name' => 'ubah','route_name' => 'accounting-jurnal-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '16','resource_id' => '3','name' => 'hapus','route_name' => 'accounting-jurnal-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '17','resource_id' => '3','name' => 'posting','route_name' => 'accounting-jurnal-posted','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '18','resource_id' => '4','name' => 'saldo awal','route_name' => 'accounting-neraca-saldo-awal','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '19','resource_id' => '4','name' => 'tutup buku','route_name' => 'accounting-neraca-tutup-buku','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '310','resource_id' => '68','name' => 'tampil','route_name' => 'accounting-bank','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '311','resource_id' => '69','name' => 'tampil','route_name' => 'accounting-creditcard','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '20','resource_id' => '5','name' => 'tampil','route_name' => 'accounting-kastype','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '21','resource_id' => '5','name' => 'tambah','route_name' => 'accounting-kastype-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '22','resource_id' => '5','name' => 'ubah','route_name' => 'accounting-kastype-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '23','resource_id' => '5','name' => 'hapus','route_name' => 'accounting-kastype-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '24','resource_id' => '6','name' => 'tampil','route_name' => 'accounting-kas','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '25','resource_id' => '6','name' => 'tambah','route_name' => 'ccounting-kas-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '26','resource_id' => '6','name' => 'ubah','route_name' => 'accounting-kas-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '27','resource_id' => '6','name' => 'hapus','route_name' => 'accounting-kas-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '28','resource_id' => '7','name' => 'tampil','route_name' => 'accounting-currency','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '29','resource_id' => '7','name' => 'rate','route_name' => 'accounting-currency-rate','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '30','resource_id' => '7','name' => 'hapus','route_name' => 'accounting-currency-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '31','resource_id' => '8','name' => 'account','route_name' => 'accounting-report-account','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '32','resource_id' => '8','name' => 'saldo','route_name' => 'accounting-report-saldo','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '33','resource_id' => '8','name' => 'jurnal','route_name' => 'accounting-report-jurnal','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '34','resource_id' => '8','name' => 'buku besar','route_name' => 'accounting-report-bukubesar','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '35','resource_id' => '8','name' => 'laba rugi','route_name' => 'accounting-report-labarugi','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '36','resource_id' => '8','name' => 'laba rugi detail','route_name' => 'accounting-report-labarugi_detail','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '37','resource_id' => '8','name' => 'aktiva','route_name' => 'accounting-report-aktiva','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '38','resource_id' => '8','name' => 'neraca','route_name' => 'accounting-report-neraca','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '39','resource_id' => '8','name' => 'neraca detail','route_name' => 'accounting-report-neraca_detail','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '40','resource_id' => '8','name' => 'trans kas & bank','route_name' => 'accounting-report-trans-kas','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '41','resource_id' => '9','name' => 'tampil','route_name' => 'accounting-aktiva','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '42','resource_id' => '9','name' => 'tambah','route_name' => 'accounting-aktiva-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '43','resource_id' => '9','name' => 'ubah','route_name' => 'accounting-aktiva-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '44','resource_id' => '9','name' => 'hapus','route_name' => 'accounting-aktiva-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '45','resource_id' => '9','name' => 'penyusutan','route_name' => 'accounting-aktiva-penyusutan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '46','resource_id' => '9','name' => 'hapus penyusutan','route_name' => 'accounting-aktiva-penyusutan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '47','resource_id' => '10','name' => 'tampil','route_name' => 'accounting-aktiva-group','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '48','resource_id' => '10','name' => 'tambah','route_name' => 'accounting-aktiva-group-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '49','resource_id' => '10','name' => 'ubah','route_name' => 'accounting-aktiva-group-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '50','resource_id' => '10','name' => 'hapus','route_name' => 'accounting-aktiva-group-hapus','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '51','resource_id' => '11','name' => 'tampil','route_name' => 'setup-department','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '52','resource_id' => '11','name' => 'tambah','route_name' => 'setup-department-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '53','resource_id' => '11','name' => 'ubah','route_name' => 'setup-department-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '54','resource_id' => '11','name' => 'hapus','route_name' => 'setup-department-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '55','resource_id' => '12','name' => 'tampil','route_name' => 'setup-user','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '56','resource_id' => '12','name' => 'tambah','route_name' => 'setup-user-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '57','resource_id' => '12','name' => 'ubah','route_name' => 'setup-user-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '58','resource_id' => '12','name' => 'hapus','route_name' => 'setup-user-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '59','resource_id' => '13','name' => 'tampil','route_name' => 'setup-room','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '60','resource_id' => '13','name' => 'tambah','route_name' => 'setup-room-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '61','resource_id' => '13','name' => 'ubah','route_name' => 'setup-room-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '62','resource_id' => '13','name' => 'hapus','route_name' => 'setup-room-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '63','resource_id' => '14','name' => 'tampil','route_name' => 'setup-room-type','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '64','resource_id' => '14','name' => 'tambah','route_name' => 'setup-room-type-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '65','resource_id' => '14','name' => 'ubah','route_name' => 'setup-room-type-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '66','resource_id' => '14','name' => 'hapus','route_name' => 'setup-room-type-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '67','resource_id' => '15','name' => 'tampil','route_name' => 'setup-room-facility','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '68','resource_id' => '15','name' => 'tambah','route_name' => 'setup-room-facility-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '69','resource_id' => '15','name' => 'ubah','route_name' => 'setup-room-facility-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '70','resource_id' => '15','name' => 'hapus','route_name' => 'setup-room-facility-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '71','resource_id' => '16','name' => 'tampil','route_name' => 'setup-bed-type','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '72','resource_id' => '16','name' => 'tambah','route_name' => 'setup-bed-type-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '73','resource_id' => '16','name' => 'ubah','route_name' => 'setup-bed-type-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '74','resource_id' => '16','name' => 'hapus','route_name' => 'setup-bed-type-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '75','resource_id' => '17','name' => 'tampil','route_name' => 'setup-room','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '76','resource_id' => '17','name' => 'tambah','route_name' => 'setup-room-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '77','resource_id' => '17','name' => 'ubah','route_name' => 'setup-room-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '78','resource_id' => '17','name' => 'hapus','route_name' => 'setup-room-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '79','resource_id' => '18','name' => 'atur harga','route_name' => 'setup-room-rate','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '80','resource_id' => '19','name' => 'tampil','route_name' => 'setup-periodic-rate','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '81','resource_id' => '19','name' => 'tambah','route_name' => 'setup-periodic-rate-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '82','resource_id' => '19','name' => 'ubah','route_name' => 'setup-periodic-rate-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '83','resource_id' => '19','name' => 'hapus','route_name' => 'setup-periodic-rate-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '84','resource_id' => '20','name' => 'opsi','route_name' => 'setup-options','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '85','resource_id' => '21','name' => 'tampil','route_name' => 'frontdesk-guest','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '86','resource_id' => '21','name' => 'tambah','route_name' => 'frontdesk-guest-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '87','resource_id' => '21','name' => 'ubah','route_name' => 'frontdesk-guest-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '88','resource_id' => '21','name' => 'hapus','route_name' => 'frontdesk-guest-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '89','resource_id' => '22','name' => 'tampil','route_name' => 'frontdesk-agent','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '90','resource_id' => '22','name' => 'tambah','route_name' => 'frontdesk-agent-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '91','resource_id' => '22','name' => 'ubah','route_name' => 'frontdesk-agent-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '92','resource_id' => '22','name' => 'hapus','route_name' => 'frontdesk-agent-hapus','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '93','resource_id' => '23','name' => 'tampil','route_name' => 'frontdesk-reservation','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '94','resource_id' => '23','name' => 'tambah','route_name' => 'frontdesk-reservation-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '95','resource_id' => '23','name' => 'ubah','route_name' => 'frontdesk-reservation-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '96','resource_id' => '23','name' => 'hapus','route_name' => 'frontdesk-reservation-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '97','resource_id' => '23','name' => 'chart','route_name' => 'frontdesk-reservation-chart','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '98','resource_id' => '24','name' => 'tampil','route_name' => 'frontdesk-addchargetype','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '99','resource_id' => '24','name' => 'tambah','route_name' => 'frontdesk-addchargetype-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '100','resource_id' => '24','name' => 'ubah','route_name' => 'frontdesk-addchargetype-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '101','resource_id' => '24','name' => 'hapus','route_name' => 'frontdesk-addchargetype-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '102','resource_id' => '25','name' => 'tampil','route_name' => 'frontdesk-addcharge','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '103','resource_id' => '25','name' => 'tambah','route_name' => 'frontdesk-addcharge-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '104','resource_id' => '25','name' => 'ubah','route_name' => 'frontdesk-addcharge-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '105','resource_id' => '25','name' => 'hapus','route_name' => 'frontdesk-addcharge-hapus','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '106','resource_id' => '26','name' => 'ubah','route_name' => 'frontdesk-deposit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '107','resource_id' => '26','name' => 'hapus','route_name' => 'frontdesk-deposit-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '108','resource_id' => '27','name' => 'tampil','route_name' => 'frondesk-checkin','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '109','resource_id' => '27','name' => 'tambah','route_name' => 'frondesk-checkin-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '110','resource_id' => '27','name' => 'ubah','route_name' => 'frondesk-checkin-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '111','resource_id' => '27','name' => 'hapus','route_name' => 'frondesk-checkin-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '112','resource_id' => '28','name' => 'tampil','route_name' => 'frondesk-checkingroup','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '113','resource_id' => '28','name' => 'tambah','route_name' => 'frondesk-checkingroup-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '114','resource_id' => '28','name' => 'ubah','route_name' => 'frondesk-checkingroup-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '115','resource_id' => '31','name' => 'tampil','route_name' => 'housekeeping-laundry-tarif','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '116','resource_id' => '31','name' => 'tambah','route_name' => 'housekeeping-laundry-tarif-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '117','resource_id' => '31','name' => 'ubah','route_name' => 'housekeeping-laundry-tarif-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '118','resource_id' => '31','name' => 'simpan','route_name' => 'housekeeping-laundry-tarif-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '119','resource_id' => '31','name' => 'hapus','route_name' => 'housekeeping-laundry-tarif-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '120','resource_id' => '32','name' => 'tampil','route_name' => 'housekeeping-laundry-layanan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '121','resource_id' => '32','name' => 'tambah','route_name' => 'housekeeping-laundry-layanan-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '122','resource_id' => '32','name' => 'ubah','route_name' => 'housekeeping-laundry-layanan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '123','resource_id' => '32','name' => 'simpan','route_name' => 'housekeeping-laundry-layanan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '124','resource_id' => '32','name' => 'hapus','route_name' => 'housekeeping-laundry-layanan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '125','resource_id' => '33','name' => 'tampil','route_name' => 'housekeeping-barangtemuan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '126','resource_id' => '33','name' => 'tambah','route_name' => 'housekeeping-barangtemuan-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '127','resource_id' => '33','name' => 'ubah','route_name' => 'housekeeping-barangtemuan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '128','resource_id' => '33','name' => 'simpan','route_name' => 'housekeeping-barangtemuan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '129','resource_id' => '33','name' => 'hapus','route_name' => 'housekeeping-barangtemuan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '130','resource_id' => '34','name' => 'tampil','route_name' => 'housekeeping-barang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '131','resource_id' => '34','name' => 'tambah','route_name' => 'housekeeping-barang-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '132','resource_id' => '34','name' => 'ubah','route_name' => 'housekeeping-barang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '133','resource_id' => '34','name' => 'simpan','route_name' => 'housekeeping-barang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '134','resource_id' => '34','name' => 'hapus','route_name' => 'housekeeping-barang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '135','resource_id' => '35','name' => 'tampil','route_name' => 'housekeeping-barangkembali','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '136','resource_id' => '35','name' => 'tambah','route_name' => 'housekeeping-barangkembali-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '137','resource_id' => '35','name' => 'ubah','route_name' => 'housekeeping-barangkembali-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '138','resource_id' => '35','name' => 'simpan','route_name' => 'housekeeping-barangkembali-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '139','resource_id' => '35','name' => 'hapus','route_name' => 'housekeeping-barangkembali-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '140','resource_id' => '36','name' => 'tampil','route_name' => 'houskeeping-roomservice','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '141','resource_id' => '36','name' => 'tambah','route_name' => 'houskeeping-roomservice-form','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '142','resource_id' => '36','name' => 'ubah','route_name' => 'houskeeping-roomservice-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '143','resource_id' => '36','name' => 'simpan','route_name' => 'houskeeping-roomservice-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '144','resource_id' => '36','name' => 'hapus','route_name' => 'houskeeping-roomservice-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '145','resource_id' => '37','name' => 'tampil','route_name' => 'houskeeping-pinjambarang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '146','resource_id' => '37','name' => 'tambah','route_name' => 'houskeeping-pinjambarang-form','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '147','resource_id' => '37','name' => 'ubah','route_name' => 'houskeeping-pinjambarang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '148','resource_id' => '37','name' => 'simpan','route_name' => 'houskeeping-pinjambarang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '149','resource_id' => '37','name' => 'hapus','route_name' => 'houskeeping-pinjambarang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '150','resource_id' => '38','name' => 'tampil','route_name' => 'houskeeping-jenis-pinjambarang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '151','resource_id' => '38','name' => 'tambah','route_name' => 'houskeeping-jenis-pinjambarang-form','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '152','resource_id' => '38','name' => 'ubah','route_name' => 'houskeeping-jenis-pinjambarang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '153','resource_id' => '38','name' => 'simpan','route_name' => 'houskeeping-jenis-pinjambarang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '154','resource_id' => '38','name' => 'hapus','route_name' => 'houskeeping-jenis-pinjambarang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '155','resource_id' => '39','name' => 'tampil','route_name' => 'menu','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '156','resource_id' => '39','name' => 'tambah','route_name' => 'restoran-menu-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '157','resource_id' => '39','name' => 'ubah','route_name' => 'restoran-menu-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '158','resource_id' => '39','name' => 'hapus','route_name' => 'restoran-menu-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '159','resource_id' => '39','name' => 'simpan','route_name' => 'restoran-menu-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '160','resource_id' => '40','name' => 'tampil','route_name' => 'menukategori','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '161','resource_id' => '40','name' => 'tambah','route_name' => 'menukategori-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '162','resource_id' => '40','name' => 'ubah','route_name' => 'menukategori-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '163','resource_id' => '40','name' => 'hapus','route_name' => 'menukategori-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '164','resource_id' => '40','name' => 'simpan','route_name' => 'menukategori-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '165','resource_id' => '41','name' => 'tampil','route_name' => 'statusmeja','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '166','resource_id' => '42','name' => 'tampil','route_name' => 'kasir','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '167','resource_id' => '42','name' => 'simpan','route_name' => 'kasir-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '168','resource_id' => '43','name' => 'tampil','route_name' => 'gudang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '169','resource_id' => '43','name' => 'tambah','route_name' => 'gudang-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '170','resource_id' => '43','name' => 'ubah','route_name' => 'gudang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '171','resource_id' => '43','name' => 'hapus','route_name' => 'gudang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '172','resource_id' => '43','name' => 'simpan','route_name' => 'gudang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '173','resource_id' => '44','name' => 'tampil','route_name' => 'meja','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '174','resource_id' => '44','name' => 'tambah','route_name' => 'meja-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '175','resource_id' => '44','name' => 'ubah','route_name' => 'meja-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '176','resource_id' => '44','name' => 'hapus','route_name' => 'meja-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '177','resource_id' => '44','name' => 'simpan','route_name' => 'meja-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '178','resource_id' => '45','name' => 'tampil','route_name' => 'pelanggan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '179','resource_id' => '45','name' => 'tambah','route_name' => 'pelanggan-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '180','resource_id' => '45','name' => 'ubah','route_name' => 'pelanggan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '181','resource_id' => '45','name' => 'hapus','route_name' => 'pelanggan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '182','resource_id' => '45','name' => 'simpan','route_name' => 'pelanggan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '183','resource_id' => '46','name' => 'laporan','route_name' => 'report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '184','resource_id' => '46','name' => 'menu','route_name' => 'menu-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '185','resource_id' => '46','name' => 'penjualan menu','route_name' => 'menu-penjualan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '186','resource_id' => '46','name' => 'pemakaian bahan','route_name' => 'pemakaianbahan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '187','resource_id' => '46','name' => 'penjualan','route_name' => 'restoran-penjualan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '188','resource_id' => '46','name' => 'laba penjualan','route_name' => 'restoran-labapenjualan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '189','resource_id' => '47','name' => 'tampil','route_name' => 'pesanan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '190','resource_id' => '47','name' => 'tambah','route_name' => 'pesanan-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '191','resource_id' => '47','name' => 'ubah','route_name' => 'pesanan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '192','resource_id' => '47','name' => 'hapus','route_name' => 'pesanan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '193','resource_id' => '47','name' => 'simpan','route_name' => 'pesanan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '194','resource_id' => '48','name' => 'tampil','route_name' => 'pembelian-supplier','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '195','resource_id' => '48','name' => 'tambah','route_name' => 'pembelian-supplier-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '196','resource_id' => '48','name' => 'ubah','route_name' => 'pembelian-supplier-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '197','resource_id' => '48','name' => 'simpan','route_name' => 'pembelian-supplier-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '198','resource_id' => '48','name' => 'hapus','route_name' => 'pembelian-supplier-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '199','resource_id' => '49','name' => 'tampil','route_name' => 'daftar-pembelian','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '200','resource_id' => '49','name' => 'tambah','route_name' => 'daftar-pembelian-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '201','resource_id' => '49','name' => 'ubah','route_name' => 'daftar-pembelian-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '202','resource_id' => '49','name' => 'simpan','route_name' => 'daftar-pembelian-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '203','resource_id' => '49','name' => 'hapus','route_name' => 'daftar-pembelian-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '204','resource_id' => '50','name' => 'tampil','route_name' => 'retur-pembelian','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '205','resource_id' => '50','name' => 'tambah','route_name' => 'retur-pembelian-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '206','resource_id' => '50','name' => 'ubah','route_name' => 'retur-pembelian-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '207','resource_id' => '50','name' => 'simpan','route_name' => 'retur-pembelian-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '208','resource_id' => '50','name' => 'hapus','route_name' => 'retur-pembelian-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '209','resource_id' => '51','name' => 'suplier','route_name' => 'pembelian-report-supplier','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '210','resource_id' => '51','name' => 'semua','route_name' => 'pembelian-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '211','resource_id' => '51','name' => 'detail','route_name' => 'pembeliandetail-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '212','resource_id' => '51','name' => 'pembelian','route_name' => 'pembelian-report-purchase','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '213','resource_id' => '51','name' => 'retur pembelian','route_name' => 'retur-pembelian-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '214','resource_id' => '51','name' => 'cetak pembelian','route_name' => 'retur-pembelian-print','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '215','resource_id' => '52','name' => 'tampil','route_name' => 'logistic-warehouse','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '216','resource_id' => '52','name' => 'tambah','route_name' => 'logistic-warehouse-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '217','resource_id' => '52','name' => 'ubah','route_name' => 'logistic-warehouse-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '218','resource_id' => '52','name' => 'simpan','route_name' => 'logistic-warehouse-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '219','resource_id' => '52','name' => 'hapus','route_name' => 'logistic-warehouse-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '220','resource_id' => '53','name' => 'tampil','route_name' => 'logistic-good','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '221','resource_id' => '53','name' => 'tambah','route_name' => 'logistic-good-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '222','resource_id' => '53','name' => 'ubah','route_name' => 'logistic-good-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '223','resource_id' => '53','name' => 'simpan','route_name' => 'logistic-good-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '224','resource_id' => '53','name' => 'hapus','route_name' => 'logistic-good-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '225','resource_id' => '54','name' => 'tampil','route_name' => 'logistic-conversion','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '226','resource_id' => '54','name' => 'tambah','route_name' => 'logistic-conversion-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '227','resource_id' => '54','name' => 'ubah','route_name' => 'logistic-conversion-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '228','resource_id' => '54','name' => 'simpan','route_name' => 'logistic-conversion-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '229','resource_id' => '54','name' => 'hapus','route_name' => 'logistic-conversion-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '230','resource_id' => '55','name' => 'tampil','route_name' => 'logistic-category','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '231','resource_id' => '55','name' => 'tambah','route_name' => 'logistic-category-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '232','resource_id' => '55','name' => 'ubah','route_name' => 'logistic-category-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '233','resource_id' => '55','name' => 'simpan','route_name' => 'logistic-category-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '234','resource_id' => '55','name' => 'hapus','route_name' => 'logistic-category-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '235','resource_id' => '56','name' => 'tampil','route_name' => 'logistic-unit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '236','resource_id' => '56','name' => 'tambah','route_name' => 'logistic-unit-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '237','resource_id' => '56','name' => 'ubah','route_name' => 'logistic-unit-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '238','resource_id' => '56','name' => 'simpan','route_name' => 'logistic-unit-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '239','resource_id' => '56','name' => 'hapus','route_name' => 'logistic-unit-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '240','resource_id' => '57','name' => 'tampil','route_name' => 'logistic-loss-item','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '241','resource_id' => '57','name' => 'tambah','route_name' => 'logistic-loss-item-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '242','resource_id' => '57','name' => 'ubah','route_name' => 'logistic-loss-item-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '243','resource_id' => '57','name' => 'simpan','route_name' => 'logistic-loss-item-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '244','resource_id' => '57','name' => 'hapus','route_name' => 'logistic-loss-item-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '245','resource_id' => '57','name' => 'laporan','route_name' => 'logistic-loss-item-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '246','resource_id' => '58','name' => 'tampil','route_name' => 'logistic-purchase-request','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '247','resource_id' => '58','name' => 'tambah','route_name' => 'logistic-purchase-request-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '248','resource_id' => '58','name' => 'ubah','route_name' => 'logistic-purchase-request-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '249','resource_id' => '58','name' => 'simpan','route_name' => 'logistic-purchase-request-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '250','resource_id' => '58','name' => 'hapus','route_name' => 'logistic-purchase-request-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '251','resource_id' => '58','name' => 'laporan','route_name' => 'logistic-purchase-request-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '252','resource_id' => '59','name' => 'tampil','route_name' => 'logistic-usage','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '253','resource_id' => '59','name' => 'tambah','route_name' => 'logistic-usage-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '254','resource_id' => '59','name' => 'ubah','route_name' => 'logistic-usage-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '255','resource_id' => '59','name' => 'simpan','route_name' => 'logistic-usage-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '256','resource_id' => '59','name' => 'hapus','route_name' => 'logistic-usage-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '257','resource_id' => '59','name' => 'laporan','route_name' => 'logistic-usage-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '258','resource_id' => '60','name' => 'tampil','route_name' => 'logistic-mutation','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '259','resource_id' => '60','name' => 'tambah','route_name' => 'logistic-mutation-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '260','resource_id' => '60','name' => 'ubah','route_name' => 'logistic-mutation-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '261','resource_id' => '60','name' => 'simpan','route_name' => 'logistic-mutation-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '262','resource_id' => '60','name' => 'hapus','route_name' => 'logistic-mutation-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '263','resource_id' => '60','name' => 'laporan','route_name' => 'logistic-mutation-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '264','resource_id' => '61','name' => 'tampil','route_name' => 'logistic-stocktaking','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '265','resource_id' => '61','name' => 'tambah','route_name' => 'logistic-stocktaking-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '266','resource_id' => '61','name' => 'ubah','route_name' => 'logistic-stocktaking-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '267','resource_id' => '61','name' => 'simpan','route_name' => 'logistic-stocktaking-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '268','resource_id' => '61','name' => 'hapus','route_name' => 'logistic-stocktaking-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '269','resource_id' => '61','name' => 'laporan','route_name' => 'logistic-stocktaking-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '270','resource_id' => '62','name' => 'pemakaian','route_name' => 'logistic-usage-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '271','resource_id' => '62','name' => 'revisi','route_name' => 'logistic-revision-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '272','resource_id' => '62','name' => 'barang hilang','route_name' => 'logistic-loss-item-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '273','resource_id' => '62','name' => 'mutasi','route_name' => 'logistic-mutation-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '274','resource_id' => '62','name' => 'penerimaan','route_name' => 'logistic-receive-report-all','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '275','resource_id' => '62','name' => 'kartu stok','route_name' => 'logistic-stock-card','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '276','resource_id' => '62','name' => 'stok','route_name' => 'logistic-stock-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '277','resource_id' => '63','name' => 'tampil','route_name' => 'logistic-revision','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '278','resource_id' => '63','name' => 'tambah','route_name' => 'logistic-revision-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '279','resource_id' => '63','name' => 'ubah','route_name' => 'logistic-revision-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '280','resource_id' => '63','name' => 'simpan','route_name' => 'logistic-revision-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '281','resource_id' => '63','name' => 'hapus','route_name' => 'logistic-revision-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '282','resource_id' => '63','name' => 'laporan','route_name' => 'logistic-revision-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '283','resource_id' => '64','name' => 'tampil','route_name' => 'logistic-receive','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '284','resource_id' => '64','name' => 'tambah','route_name' => 'logistic-receive-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '285','resource_id' => '64','name' => 'ubah','route_name' => 'logistic-receive-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '286','resource_id' => '64','name' => 'simpan','route_name' => 'logistic-receive-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '287','resource_id' => '64','name' => 'hapus','route_name' => 'logistic-receive-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '288','resource_id' => '64','name' => 'laporan','route_name' => 'logistic-receive-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '289','resource_id' => '65','name' => 'barcode','route_name' => 'logistic-barcode','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                array('id' => '290','resource_id' => '66','name' => 'tampil','route_name' => 'logistic-company','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '291','resource_id' => '66','name' => 'tambah','route_name' => 'logistic-company-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '292','resource_id' => '66','name' => 'ubah','route_name' => 'logistic-company-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '293','resource_id' => '66','name' => 'simpan','route_name' => 'logistic-company-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '294','resource_id' => '66','name' => 'hapus','route_name' => 'logistic-company-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //checkout
                                array('id' => '295','resource_id' => '29','name' => 'tampil','route_name' => 'frondesk-checkout','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '296','resource_id' => '29','name' => 'tambah','route_name' => 'frondesk-checkout-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '298','resource_id' => '29','name' => 'simpan','route_name' => 'frondesk-checkout-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '299','resource_id' => '29','name' => 'hapus','route_name' => 'frondesk-checkout-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //status kamar
                                array('id' => '300','resource_id' => '30','name' => 'tampil','route_name' => 'frontdesk-roomstatus','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '301','resource_id' => '30','name' => 'tambah','route_name' => 'frontdesk-roomstatus-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '302','resource_id' => '30','name' => 'edit','route_name' => 'frontdesk-roomstatus-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '303','resource_id' => '30','name' => 'simpan','route_name' => 'frontdesk-roomstatus-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '304','resource_id' => '30','name' => 'hapus','route_name' => 'frontdesk-roomstatus-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //gedung
                                array('id' => '305','resource_id' => '67','name' => 'tampil','route_name' => 'setup-building','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '306','resource_id' => '67','name' => 'tambah','route_name' => 'setup-building-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '307','resource_id' => '67','name' => 'edit','route_name' => 'setup-building-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '308','resource_id' => '67','name' => 'simpan','route_name' => 'setup-building-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '309','resource_id' => '67','name' => 'hapus','route_name' => 'setup-building-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //pendapatan
                                array('id' => '312','resource_id' => '70','name' => 'Restorante','route_name' => 'pendapatan-restorante','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '313','resource_id' => '70','name' => 'Whitehouse','route_name' => 'pendapatan-whitehouse','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '314','resource_id' => '70','name' => 'Spa','route_name' => 'pendapatan-spa','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '315','resource_id' => '70','name' => 'Checkout','route_name' => 'pendapatan-checkout','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '316','resource_id' => '70','name' => 'Rekap','route_name' => 'pendapatan-rekap','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                
                                //Spa Report
                                array('id' => '317','resource_id' => '76','name' => 'Terapis','route_name' => 'terapis-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '318','resource_id' => '76','name' => 'Daftar Layanan','route_name' => 'layanan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '319','resource_id' => '76','name' => 'Rekap Penjualan Spa','route_name' => 'report-rekap-penjualan-spa','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '320','resource_id' => '76','name' => 'Laporan Penjualan Spa','route_name' => 'laporan-penjualan-spa-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Spa Kasir
                                array('id' => '321','resource_id' => '71','name' => 'tampil','route_name' => 'kasirspa','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '322','resource_id' => '71','name' => 'tambah','route_name' => 'kasirspa-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '323','resource_id' => '71','name' => 'edit','route_name' => 'kasirspa-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '324','resource_id' => '71','name' => 'simpan','route_name' => 'kasirspa-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '325','resource_id' => '71','name' => 'hapus','route_name' => 'kasirspa-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Spa Kategori Layanan
                                array('id' => '326','resource_id' => '72','name' => 'tampil','route_name' => 'kategorilayanan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '327','resource_id' => '72','name' => 'tambah','route_name' => 'kategorilayanan-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '328','resource_id' => '72','name' => 'edit','route_name' => 'kategorilayanan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '329','resource_id' => '72','name' => 'simpan','route_name' => 'kategorilayanan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '330','resource_id' => '72','name' => 'hapus','route_name' => 'kategorilayanan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Spa Layanan
                                array('id' => '331','resource_id' => '73','name' => 'tampil','route_name' => 'layanan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '332','resource_id' => '73','name' => 'tambah','route_name' => 'spa-layanan-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '333','resource_id' => '73','name' => 'edit','route_name' => 'spa-layanan-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '334','resource_id' => '73','name' => 'simpan','route_name' => 'spa-layanan-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '335','resource_id' => '73','name' => 'hapus','route_name' => 'spa-layanan-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Spa Terapis
                                array('id' => '336','resource_id' => '74','name' => 'tampil','route_name' => 'terapis','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '337','resource_id' => '74','name' => 'tambah','route_name' => 'terapis-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '338','resource_id' => '74','name' => 'edit','route_name' => 'terapis-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '339','resource_id' => '74','name' => 'simpan','route_name' => 'terapis-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '340','resource_id' => '74','name' => 'hapus','route_name' => 'terapis-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Spa Gudang
                                array('id' => '341','resource_id' => '75','name' => 'tampil','route_name' => 'gudangspa','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '342','resource_id' => '75','name' => 'tambah','route_name' => 'gudangspa-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '343','resource_id' => '75','name' => 'edit','route_name' => 'gudangspa-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '344','resource_id' => '75','name' => 'simpan','route_name' => 'gudangspa-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '345','resource_id' => '75','name' => 'hapus','route_name' => 'gudangspa-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                 //Management Analisa Kamar
                                array('id' => '346','resource_id' => '77','name' => 'Ketersediaan Kamar','route_name' => 'room-availabel','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '347','resource_id' => '77','name' => 'Tingkat Hunian','route_name' => 'occupancy','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '457','resource_id' => '77','name' => 'Kamar Terfavorit','route_name' => 'room-favorite','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Management Agent & Sales
                                array('id' => '348','resource_id' => '78','name' => 'Activity Diagram','route_name' => 'activityDiagram','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '349','resource_id' => '78','name' => 'Aktifitas Penjualan','route_name' => 'salesActivity','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Management Telepon->Biaya
                                array('id' => '350','resource_id' => '79','name' => 'tampil','route_name' => 'telpbiaya','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '351','resource_id' => '79','name' => 'tambah','route_name' => 'telpbiaya-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '352','resource_id' => '79','name' => 'edit','route_name' => 'telpbiaya-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '353','resource_id' => '79','name' => 'simpan','route_name' => 'telpbiaya-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '354','resource_id' => '79','name' => 'hapus','route_name' => 'telpbiaya-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Management Telepon->Ekstention
                                array('id' => '355','resource_id' => '80','name' => 'tampil','route_name' => 'telpextention','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '356','resource_id' => '80','name' => 'tambah','route_name' => 'telpextention-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '357','resource_id' => '80','name' => 'edit','route_name' => 'telpextention-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '358','resource_id' => '80','name' => 'simpan','route_name' => 'telpextention-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '359','resource_id' => '80','name' => 'hapus','route_name' => 'telpextention-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Management Telepon->Billing
                                array('id' => '360','resource_id' => '81','name' => 'tampil','route_name' => 'telp-billing-view','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Store Barang
                                array('id' => '361','resource_id' => '82','name' => 'tampil','route_name' => 'store-barang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '362','resource_id' => '82','name' => 'tambah','route_name' => 'store-barang-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '363','resource_id' => '82','name' => 'edit','route_name' => 'store-barang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '364','resource_id' => '82','name' => 'simpan','route_name' => 'store-barang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '365','resource_id' => '82','name' => 'hapus','route_name' => 'store-barang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Store Kasir
                                array('id' => '366','resource_id' => '83','name' => 'tampil','route_name' => 'store-kasir','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '367','resource_id' => '83','name' => 'tambah','route_name' => 'store-kasir-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '368','resource_id' => '83','name' => 'edit','route_name' => 'store-kasir-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '369','resource_id' => '83','name' => 'simpan','route_name' => 'store-kasir-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '370','resource_id' => '83','name' => 'hapus','route_name' => 'store-kasir-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Store Gudang
                                array('id' => '371','resource_id' => '84','name' => 'tampil','route_name' => 'store-gudang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '372','resource_id' => '84','name' => 'tambah','route_name' => 'store-gudang-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '373','resource_id' => '84','name' => 'edit','route_name' => 'store-gudang-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '374','resource_id' => '84','name' => 'simpan','route_name' => 'store-gudang-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '375','resource_id' => '84','name' => 'hapus','route_name' => 'store-gudang-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //Store Laporan
                                array('id' => '376','resource_id' => '85','name' => 'tampil','route_name' => 'store-laporan-penjualan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                //add resource action other(tambahan menu)

                                    //accounting laporan deposit
                                array('id' => '377','resource_id' => '8','name' => 'deposit','route_name' => 'accu-deposit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //front desk laporan tamu (arrival, departure, guest in house)
                                array('id' => '378','resource_id' => '86','name' => 'Guest in House','route_name' => 'frontdesk-guest-list','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '379','resource_id' => '86','name' => 'Arrival Guest','route_name' => 'frontdesk-guest-arrival','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '380','resource_id' => '86','name' => 'Departure Guest','route_name' => 'frontdesk-guest-departure','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //front desk pindah kamar
                                array('id' => '381','resource_id' => '87','name' => 'tampil','route_name' => 'frontdesk-roomchange','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '382','resource_id' => '87','name' => 'tambah','route_name' => 'frontdesk-roomchange-form','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '383','resource_id' => '87','name' => 'simpan','route_name' => 'frontdesk-roomchange-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '384','resource_id' => '87','name' => 'hapus','route_name' => 'frontdesk-roomchange-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //front desk reservation chart
                                array('id' => '385','resource_id' => '88','name' => 'tampil','route_name' => 'frontdesk-reservation-chart-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //front desk phone book
                                array('id' => '386','resource_id' => '89','name' => 'tampil','route_name' => 'phonebook','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '387','resource_id' => '89','name' => 'tambah','route_name' => 'phonebook-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '388','resource_id' => '89','name' => 'simpan','route_name' => 'phonebook-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '389','resource_id' => '89','name' => 'edit','route_name' => 'phonebook-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '390','resource_id' => '89','name' => 'hapus','route_name' => 'phonebook-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //front desk laporan
                                array('id' => '391','resource_id' => '90','name' => 'Daftar Kamar','route_name' => 'frontdesk-report-list-rooms','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '392','resource_id' => '90','name' => 'Rekapitulasi Kamar','route_name' => 'frontdesk-report-room-summary','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '393','resource_id' => '90','name' => 'Daftar Tamu','route_name' => 'frontdesk-report-guests','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '394','resource_id' => '90','name' => 'Riwayat Tamu','route_name' => 'frontdesk-report-guest-history-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '395','resource_id' => '90','name' => 'Reservasi','route_name' => 'frontdesk-report-reservation-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '396','resource_id' => '90','name' => 'Checkin','route_name' => 'frontdesk-report-checkin-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '397','resource_id' => '90','name' => 'Checkout','route_name' => 'frontdesk-report-checkout-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '398','resource_id' => '90','name' => 'Kasir','route_name' => 'frontdesk-report-cashier-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '399','resource_id' => '90','name' => 'Pendapatan Hotel','route_name' => 'frontdesk-report-hotel-income-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '400','resource_id' => '90','name' => 'Pendapatan Checkin','route_name' => 'frontdesk-report-checkin-income-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '401','resource_id' => '90','name' => 'Pembatalan Reservasi','route_name' => 'frontdesk-report-reservation-cancel-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '402','resource_id' => '90','name' => 'Aktivitas Tamu','route_name' => 'frontdesk-report-guest-activity-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //housekeeping Setting Status Kamar
                                array('id' => '403','resource_id' => '91','name' => 'tampil','route_name' => 'housekeeping-room-status','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '404','resource_id' => '91','name' => 'simpan','route_name' => 'housekeeping-room-status-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //housekeeping laporan
                                array('id' => '405','resource_id' => '92','name' => 'Jadwal Room Service','route_name' => 'housekeeping-report-roomserviceschedule-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '406','resource_id' => '92','name' => 'Barang Hilang','route_name' => 'housekeeping-report-baranghilang-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '407','resource_id' => '92','name' => 'Barang Temuan','route_name' => 'housekeeping-report-barangtemuan-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '408','resource_id' => '92','name' => 'Peminjaman Barang','route_name' => 'housekeeping-report-pinjambarang-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '409','resource_id' => '92','name' => 'Pemeliharaan Kamar','route_name' => 'housekeeping-report-pemeliharaankamar-filter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant restorante italia
                                array('id' => '410','resource_id' => '93','name' => 'Laporan Penjualan','route_name' => 'laporan-penjualan-report-ri','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '411','resource_id' => '93','name' => 'Rekap Penjualan','route_name' => 'restoran-report-rekap-penjualan-ri','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant kasir restorante italia
                                array('id' => '412','resource_id' => '94','name' => 'tampil','route_name' => 'kasirku','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '413','resource_id' => '94','name' => 'tambah','route_name' => 'kasirku-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '414','resource_id' => '94','name' => 'simpan','route_name' => 'kasirku-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '415','resource_id' => '94','name' => 'edit','route_name' => 'kasirku-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '416','resource_id' => '94','name' => 'hapus','route_name' => 'kasirku-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant white horse
                                array('id' => '417','resource_id' => '95','name' => 'Laporan Penjualan','route_name' => 'laporan-penjualan-report-wh','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '418','resource_id' => '95','name' => 'Rekap Penjualan','route_name' => 'restoran-report-rekap-penjualan-wh','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant kasir white horse
                                array('id' => '419','resource_id' => '96','name' => 'tampil','route_name' => 'kasirwh','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '420','resource_id' => '96','name' => 'tambah','route_name' => 'kasirwh-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '421','resource_id' => '96','name' => 'simpan','route_name' => 'kasirwh-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '422','resource_id' => '96','name' => 'edit','route_name' => 'kasirwh-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '423','resource_id' => '96','name' => 'hapus','route_name' => 'kasirwh-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant waiters
                                array('id' => '424','resource_id' => '97','name' => 'tampil','route_name' => 'waiter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '425','resource_id' => '97','name' => 'tambah','route_name' => 'waiter-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '426','resource_id' => '97','name' => 'simpan','route_name' => 'waiter-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '427','resource_id' => '97','name' => 'edit','route_name' => 'waiter-edit','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '428','resource_id' => '97','name' => 'hapus','route_name' => 'waiter-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //restaurant Laporan
                                array('id' => '429','resource_id' => '98','name' => 'waiters','route_name' => 'waiters-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '430','resource_id' => '98','name' => 'meja','route_name' => 'meja-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '431','resource_id' => '98','name' => 'penjualan menu','route_name' => 'penjualanmenu-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '432','resource_id' => '98','name' => 'penjualan','route_name' => 'laporan-penjualan-report','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '433','resource_id' => '98','name' => 'rekap penjualan','route_name' => 'restoran-report-rekap-penjualan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //setup perusahaan
                                array('id' => '434','resource_id' => '99','name' => 'tampil','route_name' => 'frontdesk-company','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '435','resource_id' => '99','name' => 'tambah','route_name' => 'frontdesk-company-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '436','resource_id' => '99','name' => 'simpan','route_name' => 'frontdesk-company-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '437','resource_id' => '99','name' => 'edit','route_name' => 'frontdesk-company-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '438','resource_id' => '99','name' => 'hapus','route_name' => 'frontdesk-company-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //setup jenis status kamar
                                array('id' => '439','resource_id' => '100','name' => 'tampil','route_name' => 'setup-room-status-type','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '440','resource_id' => '100','name' => 'tambah','route_name' => 'room-status-type-add','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '441','resource_id' => '100','name' => 'simpan','route_name' => 'room-status-type-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '442','resource_id' => '100','name' => 'edit','route_name' => 'room-status-type-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '443','resource_id' => '100','name' => 'hapus','route_name' => 'room-status-type-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //setup deskripsi kamar
                                array('id' => '444','resource_id' => '101','name' => 'tampil','route_name' => 'setup-room-description','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '445','resource_id' => '101','name' => 'tambah','route_name' => 'setup-room-description-new','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '446','resource_id' => '101','name' => 'simpan','route_name' => 'setup-room-description-save','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '447','resource_id' => '101','name' => 'edit','route_name' => 'setup-room-description-update','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '448','resource_id' => '101','name' => 'hapus','route_name' => 'setup-room-description-delete','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //accounting laba rugi
                                array('id' => '449','resource_id' => '102','name' => 'Pengeluaran','route_name' => 'accounting-pengeluaran','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '450','resource_id' => '103','name' => 'Laba Rugi','route_name' => 'accounting-labarugi','sequence' => '0','created_at' => NULL,'updated_at' => NULL),

                                    //logistik Request Barang
                                array('id' => '451','resource_id' => '104','name' => 'Permintaan Barang','route_name' => 'logistic-purchase-request-request','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                               
                                
                                     //Management Restorant
                                array('id' => '452','resource_id' => '105','name' => 'Meja Terfavorit','route_name' => 'favorite-table','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '453','resource_id' => '105','name' => 'Menu Terfavorit','route_name' => 'favorite-menu','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '454','resource_id' => '105','name' => 'KInerja Waiter','route_name' => 'kinerja-waiter','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //Management Tamu
                                array('id' => '455','resource_id' => '106','name' => 'Tamu Terfavorit','route_name' => 'favorite-guests','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '456','resource_id' => '106','name' => 'Ulang Tahun Tamu','route_name' => 'guests-birthday','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //Management Spa
                                array('id' => '458','resource_id' => '107','name' => 'Kinerja Terapis','route_name' => 'kinerja-terapis','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '459','resource_id' => '107','name' => 'Layanan Terfavorit','route_name' => 'favorite-layanan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //Management Jobdesc
                                    array('id' => '460','resource_id' => '108','name' => 'Tampil','route_name' => 'tampil-board','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //Management Restorant
                                array('id' => '461','resource_id' => '105','name' => 'Penjualan Perjam','route_name' => 'penjualan-perjam','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '462','resource_id' => '105','name' => 'Penjualan Perhari','route_name' => 'penjualan-perhari','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                //Management Store
                                array('id' => '463','resource_id' => '109','name' => 'Penjualan Perjam','route_name' => 'store-penjualan-perjam','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '464','resource_id' => '109','name' => 'Penjualan Perhari','route_name' => 'store-penjualan-perhari','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '465','resource_id' => '110','name' => 'Tampil','route_name' => 'analisa-keuangan','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '466','resource_id' => '111','name' => 'Tampil','route_name' => 'analisa-reservasi','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                array('id' => '467','resource_id' => '112','name' => 'Tampil','route_name' => 'analisa-checkin','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                // setup gudang
                                array('id' => '468','resource_id' => '113','name' => 'Tampil','route_name' => 'setup-gudang','sequence' => '0','created_at' => NULL,'updated_at' => NULL),
                                );
             Capsule::table('resource_actions')->insert($resource_actions);   

    }
}
